version: '3.8'

services:
  vim-assignment:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - NOTIFICATION_SERVER_URL=http://ISR-PF3RKYVY:5001
    depends_on:
      - notification-service

  notification-service:
    image: aryekog/backend-interview-notifications-service:0.0.2
    platform: linux/arm64/v8
    ports:
      - "5001:5001"
    environment:
      - EMAIL_RATE_LIMIT=1
      - SMS_RATE_LIMIT=1
      - RATE_LIMIT_WINDOW_MS=1000
      - ERROR_RATE=0.1 
